### ISSUE TITLE
Managing spam 

### ISSUE THREAD

**Issue by jaknz** [Digital-Preservation-Coalition/PythonStudyGroups#15]
The following user has only just created a GH account and is spamming several Python-related discussions with this ad. Any thoughts on better user management?

============
I found a Python t-shirt/What do you suggest?
Should I choose black or Grey for my T-shirt?
https://www.teechip.com/t-shirt-beautiful

_Originally posted by @John-boli in https://github.com/Digital-Preservation-Coalition/PythonStudyGroups/discussions/7#discussioncomment-8235964_

**Comment by mutanthumb** [comment]
Thanks for letting us know. I have blocked this account and have deleted the post.
