### ISSUE TITLE
Post here to request write access to the PSG Repo. This will allow you to post code to [your relevant study group folder](https://github.com/Digital-Preservation-Coalition/PythonStudyGroups/tree/main/2024%20Cohort%202).

### ISSUE THREAD

**Issue by ccllaa** [Digital-Preservation-Coalition/PythonStudyGroups#50]
Hi Sharon
I'd love to have write access to the repository of group 14. Many thanks!

**Comment by mutanthumb** [comment]
Hi I just sent you an invite, please let me know if you have any issues! 
Thanks, susan

**Comment by ccllaa** [comment]
> Hi I just sent you an invite, please let me know if you have any issues! Thanks, susan
Hi Susan, I accepted your invite and it works. Many thanks, Claudia
